stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  CI_IMAGE_FULL_NAME: "$CI_REPO:$CI_COMMIT_SHORT_SHA"

build-image:
  stage: build
  image: docker:latest
  variables:
    CI_PUSH_IMAGE_ROOT_PATH: "$CI_REGISTRY/$CI_REPO"
  before_script:
    - echo $CI_REGISTRY_PASSWORD |
      docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t "$CI_PUSH_IMAGE_ROOT_PATH:$CI_COMMIT_SHORT_SHA"
      -t "$CI_PUSH_IMAGE_ROOT_PATH:latest" .
    - docker push $CI_PUSH_IMAGE_ROOT_PATH:$CI_COMMIT_SHORT_SHA
  after_script:
    - echo "Docker image pushed at ${CI_IMAGE_FULL_NAME}"
  # only:
  #   - master

deploy:
  stage: deploy
  image: python:3
  before_script:
    - chmod 600 $GITLAB_SSH_KEY # ansible won't use key if more than read+write permissions
    - pip3 install ansible
  script:
    - ansible-playbook -i ansible/hosts ansible/playbook.yaml
      --extra-vars "image_id=$CI_IMAGE_FULL_NAME gitlab_ssh_key=$GITLAB_SSH_KEY"
  artifacts:
    paths:
      - $GITLAB_SSH_KEY_FILE
  # only:
  #   - master