stages:
  - build
  - deploy

build-image:
  stage: build
  image: docker:latest
  before_script:
    - echo $CI_REGISTRY_PASSWORD |
      docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
  only:
    - master
