---
apiVersion: v1
kind: Namespace
metadata:
  name: cv-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-docker
  namespace: cv-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-docker-nginx
  template:
    metadata:
      labels:
        app: cv-docker-nginx
    spec:
      containers:
      - name: cv-docker-nginx
        image: "{{ image_id }}"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: cv-docker-svc
  namespace: cv-docker
spec:
  selector:
    app: cv-docker-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cv-docker-ingress
  namespace: cv-docker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      # at root: "/" or at "/cv"
      - path: /(cv)?
        backend:
          serviceName: cv-docker-svc
          servicePort: 80